name: Deploy Quasar SPA to GitHub Pages

on:
  push:
    branches: [ "cicd" ]   # 👈 ใช้ branch cicd ที่คุณสร้าง

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ให้สิทธิ์ push ไปที่ gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # Quasar รองรับ Node 20

      - name: Install dependencies
        run: npm install

      - name: Build Quasar SPA
        run: npx quasar build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 🔒 ใช้ secret ของ GitHub
          publish_dir: dist/spa
